name: ci
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  ci:
    name: CI
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: npm
      - run: npm ci
      - run: npx lockfile-lint --type npm --path package-lock.json --validate-https --allowed-hosts npm
      - run: npm run lint
